[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/lead"
  to = "/.netlify/functions/lead"
  status = 200
  force = true

[[redirects]]
  from = "/api/leads"
  to = "/.netlify/functions/leads"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin"
  status = 200
  force = true
